# Generated by Django 4.1.7 on 2023-05-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
