# Generated by Django 4.1.7 on 2023-06-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='primary',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
